version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: healthmed
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/healthmed
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pgdata:
